### ISSUE TITLE
Config.ini help

### ISSUE THREAD

**Issue by Botond24** [davidwangd/OsuPlayer#2]
Can you help me with what to write in the config.ini?

**Comment by IcicleF** [comment]
`config.txt` contains the following 4 lines: 
```
/path/to/osufile.osu
MaxTime
DimThreshold
Delay
```
where:
* `MaxTime` is an integer for the maximum script running time
* `DimThreshold` is an integer threshold. Osu!'s "Backgroud dim" should be 100% to make this script work. It checks a certain pixel and starts when its brightness is lower than `DimThreshold`.
* `Delay` is an INTERESTING double. The script sleeps for `Delay` secs before it actually starts. You should finetune this for each Osu! instance.

**Please note that this is only a demonstration project for entertainment, and we offer no further maintenance.**

**Comment by Botond24** [comment]
Thank you for your response
